name: VisuaLegal
favicon: null
layout_spectrum: 0.5349
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e8f0'
    - '#1f0052'
    - '#678db2'
    - '#a6a1c0'
    - '#513c7a'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.8261584653519094
  rhythmicContrast: 0.75
purpose: []
